name: Go Build1

on:
  watch:
    types: [started]
  schedule:
    - cron: "25 */5 * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Setup
      uses: AnimMouse/setup-cloudflared@v2

    - name: Config Origin
      uses: AnimMouse/setup-cloudflared/tunnel@v2
      with:
        cloudflare_tunnel_credential: ${{ secrets.CF_CR }}
        cloudflare_tunnel_configuration: ${{ secrets.CF_CG }}
        cloudflare_tunnel_id: ${{ secrets.CF_ID }}
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.17.0'

    - name: Go Tidy
      run: |
        go mod tidy && go mod download

    - name: Run test
      run: |
        go run ./cmd/sing-box run &>/dev/null &

    - name: Clean
      if: always()
      uses: AnimMouse/setup-cloudflared/shutdown@v2
      
