name: Go Build Test

on:
  schedule:
    - cron: "25 */2 * * *"
  push:
    branches:    
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Write secret to temporary file
      run: echo "${{ secrets.API_SC }}" > xapi.txt

    - name: Install NTP and set timezone
      run: |
        sudo apt-get install -y ntpdate
        
        # 设置时区
        sudo timedatectl set-timezone Asia/Shanghai
        
        # 同步网络时间（可选，但虚拟机时间可能不准确）
        echo "同步前系统时间: $(date)"
        sudo ntpdate -s time.nist.gov
        echo "同步后系统时间: $(date)"
        
        # 显示时间信息
        echo "=== 时间信息 ==="
        date
        echo "UTC时间: $(date -u)"
        timedatectl status
      
    - name: BF Run your task
      run: |
        echo "测试任务执行时间: $(date '+%Y-%m-%d %H:%M:%S %Z')"
    
    - name: Get Network Modified
      run: |
          sudo modprobe tcp_bbr || true
          sudo modprobe sch_cake || true
          sudo sysctl -w net.core.rmem_max=8388608
          sudo sysctl -w net.core.wmem_max=8388608
          sudo sysctl -w net.ipv4.ping_group_range="0 1000"
          sudo sysctl -w net.ipv4.tcp_rmem="4096 87380 4194304"
          sudo sysctl -w net.ipv4.tcp_wmem="4096 65536 4194304"
          sudo sysctl -w net.ipv4.tcp_congestion_control=bbr
          sudo sysctl -w net.core.default_qdisc=cake
          sudo sysctl -w net.ipv4.tcp_slow_start_after_idle=0
          sudo sysctl -w net.ipv4.tcp_fastopen=3
          sudo sysctl -w net.ipv4.tcp_window_scaling=1
          sudo sysctl -w net.ipv4.tcp_adv_win_scale=2
          sudo sysctl -w net.ipv4.tcp_sack=1
          sudo sysctl -w net.ipv4.tcp_frto=2
          sudo sysctl -w net.netfilter.nf_conntrack_max=1000000
          sudo sysctl -w net.ipv4.tcp_max_syn_backlog=8192
          sudo sysctl -w vm.swappiness=10
          sudo sysctl -w net.core.rmem_default=16777216
          sudo sysctl -w net.core.wmem_default=16777216
          sudo sysctl -w vm.min_free_kbytes=65536
          sudo sysctl -w vm.zone_reclaim_mode=0
          sudo sysctl -w vm.dirty_ratio=10
          sudo sysctl -w vm.dirty_background_ratio=5
          sudo sysctl -w net.ipv4.tcp_mtu_probing=1
          sudo sysctl -w net.ipv4.ip_local_port_range="1024 65535"
          sudo sysctl -w net.ipv4.tcp_tw_reuse=1
          sudo sysctl -w net.ipv4.tcp_fin_timeout=15
          sudo sysctl -w net.ipv4.tcp_syn_retries=3
          sudo sysctl -w net.ipv4.tcp_synack_retries=3
          sudo sysctl -w net.ipv4.tcp_notsent_lowat=16384
          sudo sysctl -w net.ipv4.tcp_ecn=1
          sudo sysctl -w net.core.netdev_max_backlog=5000
          sudo sysctl -w fs.file-max=1000000
          sudo sysctl -w fs.nr_open=1000000
          sudo sysctl -w net.nf_conntrack_max=2000000
          sudo sysctl -w net.ipv4.conf.all.accept_redirects=0
          sudo sysctl -w net.ipv4.conf.all.send_redirects=0
          sudo sysctl -w net.ipv4.tcp_timestamps=1
          sudo sysctl -w net.core.somaxconn=4096
          sudo tc qdisc replace dev eth0 root cake bandwidth 980Mbit besteffort dual-srchost nat nowash
    
    - name: Setup
      uses: AnimMouse/setup-cloudflared@v2

    - name: Config Origin
      uses: AnimMouse/setup-cloudflared/tunnel@v2
      with:
        cloudflare_tunnel_credential: ${{ secrets.CF_CR }}
        cloudflare_tunnel_configuration: ${{ secrets.CF_CG }}
        cloudflare_tunnel_id: ${{ secrets.CF_ID }}
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '>=1.17.0'

    - name: Go Tidy
      run: |
        go mod tidy && go mod download

    - name: Run test
      run: |
        echo "启动测试程序 ..."
        nohup go run ./cmd/sing-box run
        echo "启动测试程序 2..."
        go run ./for/my.go

    - name: Clean
      if: always()
      uses: AnimMouse/setup-cloudflared/shutdown@v2
      
